### ISSUE TITLE
Need data model documentation

### ISSUE THREAD

**Issue by davidgristwood** [benc-uk/microservices-demoapp#7]
by that I mean fully document the data that flows in and out the middle tier (topics, etc) that are totally abstracted from any underlying store (e.g. plug in azure table storage, reddis, cosmos, etc)

**Comment by davidgristwood** [comment]
i think this just boils down to naling the Swagger definition?

**Comment by benc-uk** [comment]
I think this is resolved by the Swagger stuff? Agree?
